name: Deploy on Tag (Master)

on:
  push:
    tags:
      - 'v*'
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Push Deploy
        run: |
          DOCKER_USER="30281856"
          DOCKER_REPO="30281856/mini-api"
          IMAGE_TAG="latest"

          echo "==== Login into Docker..."
          echo "${{secrets.DOCKER_TOKEN}}" | docker login -u "$DOCKER_USER" --password-stdin

          echo "==== Build image..."
          docker build -t "${DOCKER_REPO}:${IMAGE_TAG}" .

          echo "==== Push image..."
          docker push "${DOCKER_REPO}:${IMAGE_TAG}"

          echo "==== Calling render deploy service..."
          curl https://api.render.com/deploy/${{secrets.RENDER_SERVICE_ID}}?key=${{secrets.RENDER_SERVICE_KEY}}
