name: Deploy on Tag (Master)

on:
  push:
    tags:
      - 'v*' # Por ejemplo: v1.0.0, v2.3.1
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ejecutar deploy.sh
        run: |
          DOCKER_USER="30281856"
          DOCKER_REPO="30281856/mini-api"
          IMAGE_TAG="latest"

          # docker login -u 30281856
          echo "🔐 Haciendo login a Docker..."
          echo "${{secrets.DOCKER_TOKEN}}" | docker login -u "$DOCKER_USER" --password-stdin

          echo "🔐 Buildear imagen..."
          docker build -t "${DOCKER_REPO}:${IMAGE_TAG}" .

          echo "📦 Pusheando imagen..."
          docker push "${DOCKER_REPO}:${IMAGE_TAG}"

          echo "Deploy..."
          curl https://api.render.com/deploy/${{secrets.RENDER_SERVICE_ID}}?key=${{secrets.RENDER_SERVICE_KEY}}
